[gen]
length_of_turn = 5
no_of_generations = 50  # максимальное количество поколений
population_size = 100  # количество индивидуумов в популяции
probability_of_mutation = 0.1  # вероятность мутации индивидуума
tournSel_k = 4 # количество особей, участвующих в соревновании для скрещивания
CXPB = 0.4 # вероятность скрещивания
MUTPB = 0.04  # вероятность мутации

[geom]
a_max = 0.5 # [m] Max coil radius
a_min = 0.05  # [m] Min coil radius
I = 1  # [A] Current
spacing = 1.5  # spacing for calculation domain
cp = 30  # Calculation domain points
minimal_gap = 0.003 # Diamater of the wire
figure = 'Circular'
X_side = 1
Y_side = 1
height = 0.015
coords = [[-1, 0], [-0.5, 0.866025], [0.5, 0.866025], [1, 0], [0.5, -0.866025], [-0.5, -0.866025]]
# First point MUST lie on the X axis
calculation_area = 0.9
freq = 6.78e6
material = 'Copper'